Validate values sent by form
georchestra/foncier pull request #26
Opened 2016-12-15 15:45 UTC by Vampouille

Check that year is numeric and is part of allowed year, check format
against strict list : shp, mifmid, postgis and check that proj param is
numeric.

2016-12-15 20:10 UTC, fvanderbiest requested changes
LGTM, except for the logger name

2016-12-15 20:10 UTC, fvanderbiest commented on foncier/app.py
> +logger = logging.getLogger('worker')
`logging.getLogger('app')` ?

2016-12-16 11:19 UTC, Vampouille commented on foncier/app.py
> +logger = logging.getLogger('worker')
Should be fixed by 1bacc531e25dfce7dfdb8c6a4faf2ab34039fa93

2016-12-16 11:22 UTC, fvanderbiest commented
Thanks. Please merge :-)

2016-12-16 13:04 UTC, merged